### ISSUE TITLE
manager webapp

### ISSUE THREAD

**Issue by christianwoehrle** [infrabricks/infrabricks-line#1]
tomcat contains the tomcat manager application.
this makes sense for development environments if the developer wants to deploy into an existing tomcat container again and again
however for production i would create a new container every time i want to deploy a new version, making the manager application unneccessary.
could you remove manager.war?

**Comment by rossbachp** [comment]
Update today, see changelog!
- 8.0.21
- remove manager webapps
- add tcnative experiment
- push dev images

**Comment by christianwoehrle** [comment]
thanks
